### ISSUE TITLE
infoBox Support?

### ISSUE THREAD

**Issue by Routhinator** [dylanfprice/angular-gm#21]
Is there plans to implement support for the infoBox alternative that allows greater freedom in styling?

**Comment by Fr4nks** [comment]
I need this to.

**Comment by intellix** [comment]
Actually, I was looking at implementing InfoBox as I required this. Had a look at angular-ui/google-maps and it has support there. Initially that project was quite dead and this was the only active one, but now it looks to support everything including InfoBox: http://angular-ui.github.io/angular-google-maps/#!/demo

Apologies for pointing to another project, but perhaps even looking here you can get some ideas for implementing here
