### ISSUE TITLE
Set center and zoom based on list of lats/longs

### ISSUE THREAD

**Issue by Bhaall** [dylanfprice/angular-gm#53]
I'm having much difficulty dynamically setting the center and zoom level based on a list of lats/longs.  I can't find a good example of this using AngularGM, and being such a noob with Google Maps I could definitely use some help.

I also see that there are similar questions asked here - about gm-bounds and fitBounds - but none of these have any example code.

The map's controller code:

<pre>
var lats = [], longs = [], latlng = [];

// get list of lats/longs
for (i = 0; i &lt; $scope.markersProperty.length; i++) {
    lats[i] = $scope.markersProperty[i].latitude;
    longs[i] = $scope.markersProperty[i].longitude;
    latlng.push(new google.maps.LatLng(lats[i], longs[i]));
}

$scope.bounds = new google.maps.LatLngBounds();

for (var i = 0, i &lt; latlng.length; i++) {
    $scope.bounds.extend(latlng[i]);
}

$scope.options = {
    map: {
        center: $scope.bounds.getCenter(), // this seems to work
        //zoom: 10, // how to set this dynamically based on bounds?
        mapTypeId: google.maps.MapTypeId.ROADMAP
    },
};

</pre>

The 'center' setting seems to work.
- if the list of lats/longs contains sevearl markers in, say, San Francisco, all markers can be seen;
- if this same list of lats/longs contains one additional marker in Los Angeles, the center (correctly) is between SF and LA, but the zoom is not set so that all markers can be seen.

Any help with setting the zoom (and center, if I'm doing it incorrectly here) would be greatly appreciated.

**Comment by rbose85** [comment]
:+1: nice one @Bhaall, this post has helped me a lot.
