### ISSUE TITLE
Installation process in ubuntu

### ISSUE THREAD

**Issue by johnfelipe** [dylanfprice/angular-gm#78]
Installation process in ubuntu pls

**Comment by johnfelipe** [comment]
notroot@dhcppc4:~/angular-gm$ grunt karma:server
Running "karma:server" (karma) task
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
ERROR [launcher]: Cannot start PhantomJS

INFO [launcher]: Trying to start PhantomJS again (1/2).
ERROR [launcher]: Cannot start PhantomJS

INFO [launcher]: Trying to start PhantomJS again (2/2).
ERROR [launcher]: Cannot start PhantomJS

ERROR [launcher]: PhantomJS failed 2 times (cannot start). Giving up.

**Comment by dylanfprice** [comment]
You'll need to include more information, have you installed the npm modules? Here is the info for installation, which should work across platform: https://github.com/dylanfprice/angular-gm#development
