### ISSUE TITLE
Documentation: Examples Not Loading

### ISSUE THREAD

**Issue by loganwedwards** [dylanfprice/angular-gm#80]
I see a module injection error for angular in the console.

http://dylanfprice.github.io/angular-gm/1.0.1/examples/

```javascript
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.2.27/$injector/modulerr?p0=AngularGMExample&p…gleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.27%2Fangular.min.js%3A18%3A170)
```

**Comment by dylanfprice** [comment]
Sorry looks like I forgot to push the gh-pages branch! Fixed.

**Comment by loganwedwards** [comment]
Great. Many thanks. I actually hacked Circle functionality into my own forked version, but now that you have it, i'll fire up 'ol bower again. Cheers!
