### ISSUE TITLE
Multiple marker on same location

### ISSUE THREAD

**Issue by GaurangGhinaiya** [dylanfprice/angular-gm#82]
Hello everyone

In my application i show multiple marker on map.  If marker has same location then it show only last marker while other markers are ignore.

so how can i display all marker of same location at a time.

**Comment by dylanfprice** [comment]
This may be a limitation of google maps itself. How do you expect multiple markers to be displayed at the same location?

Closing this issue. Feel free to reopen if this turns out to be a limitation of angular-gm and not google maps.
