### ISSUE TITLE
Angular 1.4.9

### ISSUE THREAD

**Issue by igler** [dylanfprice/angular-gm#85]
Got the following error when tried to update to Angular 1.4.9:

Error: [$compile:nonassign] http://errors.angularjs.org/1.4.9/$compile/nonassign?p0=undefined&p1=gmMap

Angular 1.4.8 works fine. Any ideas?

**Comment by MatthieuBarthel** [comment]
We fixed this issue by updating directives/gmMap.js with the following :
```
scope: {
  gmCenter: '=?',
  gmZoom: '=?',
  gmBounds: '=?',
  gmMapTypeId: '=?',
  gmMapOptions: '&',
  gmMapId: '&'
},
```
**!?** makes the binding optional. 

Sorry I don't have time to create a pull request right now, hope it helps.

**Comment by igler** [comment]
Thanx for the fix. A 1.0.3 release including this compatibility-feature with Angular 1.4.9 would be cool.
