### ISSUE TITLE
Labeled Markers?

### ISSUE THREAD

**Issue by rrafey** [dylanfprice/angular-gm#86]
I'd like to use Labeled Markers with AngularGM using the standard Google Maps MarkerLabel feature:

https://developers.google.com/maps/documentation/javascript/3.exp/reference#MarkerLabel

Is there an easy syntax for just creating these with the existing AngularGM version, or does this require new code?

**Comment by dylanfprice** [comment]
Yes, you can specify the label in the MarkerOptions, see the [docs for gm-marker](http://dylanfprice.github.io/angular-gm/1.0.2/docs/#/api/angulargm.directive:gmMarkers)

**Comment by rrafey** [comment]
That's cool. I didn't realize I could get more elaborate on the icon object to include labels.

Now that I have that working, I realized that Google's default MarkerLabel only allows single character labels. Is it possible to use the MarkerWithLabel extension (http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerwithlabel/docs/reference.html) with AngularGM?

If so, could you show me a very simple example of how you'd do that?

Thanks,
Rick
